create table asteroid_raw 
(

id varchar not null,
spkid varchar not null,
full_name varchar not null,
pdes varchar not null,
name varchar,
prefix varchar,
neo varchar,
pha varchar,
H varchar,
G  varchar,
M1  varchar, 
M2  varchar, 
K1  varchar, 
K2  varchar, 
PC  varchar,
diameter  varchar,
extent varchar,
albedo varchar,
rot_per varchar,
GM varchar,
BV varchar,
UB varchar,
IR varchar,
spec_B varchar,
spec_T varchar,
H_sigma varchar,
diameter_sigma varchar,
orbit_id varchar,
epoch varchar,
epoch_mjd varchar,
epoch_cal varchar,
equinox varchar,
e varchar,
a varchar,
q varchar,
i varchar,
om varchar,
w varchar,
ma varchar,
ad varchar,
n varchar,
tp varchar,
tp_cal varchar,
per varchar,
per_y varchar,
moid varchar,
moid_ld varchar,
moid_jup varchar,
t_jup varchar,
sigma_e varchar,
sigma_a varchar,
sigma_q varchar,
sigma_i varchar,
sigma_om varchar,
sigma_w varchar,
sigma_ma varchar,
sigma_ad varchar,
sigma_n varchar,
sigma_tp varchar,
sigma_per varchar,
class varchar,
producer varchar,
data_arc varchar,
first_obs varchar,
last_obs varchar,
n_obs_used varchar,
n_del_obs_used varchar,
n_dop_obs_used varchar,
condition_code varchar,
rms varchar,
two_body varchar,
A1 varchar,
A2 varchar,
A3 varchar,
DT varchar


);
